### ISSUE TITLE
`RangeError: Maximum call stack size exceeded` on large file

### ISSUE THREAD

**Issue by charlieforward9** [We-Gold/gpxjs#15]
I know. Its the edge case of edge cases. Who is using 3k files in the browser???

Well... me. And I'd love to let my friends use it too for the app I am building, [NEW HEAT](https://newheat.co). Im trying to upload a lifetime of route data without requiring any huge pre-processing of the gpx files.

I am curious if there is any possible way to make this project lighter weight so that I can get ONLY the track type, start time, end time, point time, lat, lng, and elevation, with NOTHING else that could consume more memory. 

I see there is a custom parser method, so I will explore that, but I wanted to put this hear to get a conversation started on the topic and potentially add some `options` to the `parseGPX` method to avoid implementing a whole new parsing method.

Thanks for making this awesome package!

**Comment by charlieforward9** [comment]
I just ran it again on only 450 files and got the same issue. 

Repeatably, happening here:
```
at calculateElevation (@we-gold_gpxjs.js?v=6a25f99f:80:38)
at parseGPXWithCustomParser (@we-gold_gpxjs.js?v=6a25f99f:284:148)
at parseGPX (@we-gold_gpxjs.js?v=6a25f99f:110:10)
```

**Comment by We-Gold** [comment]
Cool app idea! 

Currently, there is no way to output only minimal data for each parsed file. The active pull request (I need to get to over winter break) is trying to do a few things, including adding an options object for `parseGPX`. That would not include this feature. 

Are any of your tracks or routes particularly large? An array of points too large to fit into the call stack could cause this error.

**Comment by charlieforward9** [comment]
Thank you. Ahhh. Yes, I found it is this activity I kept running for almost a week straight while living on a field in Montana this summer. 

[12066190327.gpx.zip](https://github.com/user-attachments/files/18278190/12066190327.gpx.zip) (43mb, 4x the second largest file, ultra edge case)

Seems like this should still be handled within the package, if its too large to parse, throw a specific error (ex. `this gpx file is too large`) before the call stack is max'd out making the whole app crash. I can use the error to skip the file without crashing my app.

**Comment by We-Gold** [comment]
It's not too hard to add that error as a temporary measure. In the long run, it would be better to have an additional strategy in place for handling arrays that are too large, by splitting them up (perhaps with binary division until there is no more error). 

If you have the time, it would be ideal if you could get this started with a PR. I will be able to do it at some point, but I can't guarantee when, since I want to get the current active PR merged first. 

On a different note, you may want to consider additional in-browser storage modes. Storing all of the parsed gpx files in regular memory at once might not be feasible with so many files. I know there are multiple approaches to storing data, and you may want to look into indexedb or [origin private file system](https://developer.mozilla.org/en-US/docs/Web/API/File_System_API/Origin_private_file_system).

**Comment by charlieforward9** [comment]
@We-Gold , I appreciate your fast response.

I am rushing a year recap release for New Heat before transitioning back to my main jobs. While I can't commit now, I'm always eager to assist with open source that I use, so in the near future, you'll probably be hearing more from me, especially if the project grows and gains more contributors.

Again, thank you for providing this tool for the world to enjoy.

**Comment by We-Gold** [comment]
Just pushed a new version that fixes this. Turns out that `calculateElevation` was calling `Math.max` and `Math.min`, which are browser native functions that have the call stack issue (can't handle super large arrays). I replaced this implementation with a for loop and the issue was resolved. Hope this helps!
