### ISSUE TITLE
Extensions not parsed correctly

### ISSUE THREAD

**Issue by matteomelotti** [We-Gold/gpxjs#3]
Hello,
I'm trying to parse a gpx file with this structure:
`<trkseg>
  <trkpt lat="47.012168" lon="7.602021">
    <ele>127</ele>
    <time>2024-04-13T08:04:29.000Z</time>
    <extensions>
      <ns3:TrackPointExtension>
        <ns3:atemp>22.0</ns3:atemp>
        <ns3:hr>109</ns3:hr>
        <ns3:cad>86</ns3:cad>
      </ns3:TrackPointExtension>
    </extensions>
  </trkpt>
</trkseg>`
but when I print the extensions I get this:
<img width="225" alt="Screenshot 2024-04-14 at 19 46 10" src="https://github.com/We-Gold/gpxjs/assets/30950613/3e74d74a-56ae-48cc-914f-f02c3cc9e367">

**Comment by We-Gold** [comment]
Algorithmically, I'd presume this fails because the library attempts to parse all items inside the extensions tags as numerical, and since there is one level of hierarchy inside of extensions, it fails to parse it as a number. 

To fix this, you can either reformat the file to have all the extensions at top level:

extensions
=> ns3:atemp
=> ns3:hr

Or, you can make a PR to add support for nested extensions in a backward-compatible way. I may have time soon to try to implement this, but I can't make any promises with finals week approaching for me. It would be ideal if you could do the PR for this, especially if you need this functionality soon.

**Comment by matteomelotti** [comment]
@We-Gold opened a [PR](https://github.com/We-Gold/gpxjs/pull/4)
thanks!
