### ISSUE TITLE
CDATA parsing

### ISSUE THREAD

**Issue by yohanboniface** [We-Gold/gpxjs#7]
Hi!

Seems that CDATA values are parsed as is.
See an example file linked.

The final geojson looks like:

```json
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "name": "<![CDATA[#2RR @ BiciNuragica 2015: da Selargius a Silius]]>",
        "comment": "",
        "description": "",
        "src": "",
        "number": "",
        "link": null,
        "type": null
      },
…
```

While I'd expect the name value to be "#2RR @ BiciNuragica 2015: da Selargius a Silius".

(BTW, not sure it makes sense to set the other keys with empty values (comment, src, link…).

Thanks :)

Gpx input (.txt to be removed):
[test_with_cdata.gpx.txt](https://github.com/user-attachments/files/15965797/test_with_cdata.gpx.txt)

Geojson output:
[test_with_cdata.json](https://github.com/user-attachments/files/15965782/test_with_cdata.json)

**Comment by We-Gold** [comment]
Thanks for this!

Looks like the fix for CDATA parsing is pretty simple.

Before:

```js
const getElementValue = (parent: Element, tag: string): string => {
	const element = parent.querySelector(tag)

	// Extract and return the value within the parent element
	if (element !== null) {
		return element.innerHTML != undefined
			? element.innerHTML
			: element.childNodes[0].textContent ?? ""
	} else return ""
}
```

After:

```js
const getElementValue = (parent: Element, tag: string): string => {
	const element = parent.querySelector(tag)

	// Extract and return the value within the parent element
	if (element !== null) {
		return element.firstChild?.textContent ?? element.innerHTML ?? ""
	} else return ""
}
```

I'm interested in modifying the behavior of the library to remove null/empty values, but that will require a bit more work and testing on my end. 

Since the quick fix passed the automated tests, I'm fine making a quick commit and pushing a new version with just this one change. If you would rather wait for the null/empty removal feature (it would probably be optional for sake of avoiding breaking changes), that will take a bit longer.

Are you good with me closing this issue, making the quick change, and then working on the null/empty removal in the background?

**Comment by yohanboniface** [comment]
Sure! Thanks for quick answer and fix :)

**Comment by We-Gold** [comment]
Just pushed 1.0.10 with the fix. I don't have a timeline for the null/empty feature but I'll see what I can do.

**Comment by yohanboniface** [comment]
Thank you! :)

**Comment by We-Gold** [comment]
#8 Makes the removal of empty or null fields a default but optional behavior.
